import os
import requests
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# 🦅 AHMAD RDX - STRICT NANO BANANA ENGINE
GEMINI_API_KEY = "AIzaSyBauxWLnLg9qujUA8xxBNeaDwr14q1Mdmo"
# Aapki fresh cookies
RAW_COOKIES = "SID=g.a0006QiwLyYuoTfkKUVNkbYYzc9QRSFaHVYRXTHOmZdf4LcBTeWmcvb4ugiOJ7qPFxXeozSZ9gACgYKATsSARMSFQHGX2Mivx6862AkewAphnDGuxFS5BoVAUF8yKo5px01bMIwGF7rMUnLrxWB0076; __Secure-1PSID=g.a0006QiwLyYuoTfkKUVNkbYYzc9QRSFaHVYRXTHOmZdf4LcBTeWmtYFGIZFcxBGElmMMkAnM2AACgYKAToSARMSFQHGX2MiMEr6sujisKxyvMSg3hZstRoVAUF8yKrVem0XeaBxpjsCOrrjzpaN0076; __Secure-3PSID=g.a0006QiwLyYuoTfkKUVNkbYYzc9QRSFaHVYRXTHOmZdf4LcBTeWmhe3hUUTPF-OQY9vD9HvMzAACgYKAbUSARMSFQHGX2MiPjP4zyW_5ejnoPUMHu6V5xoVAUF8yKpY9mayOt2nqN7kbaAhh46r0076;"

@app.route('/api/nano-banana', methods=['GET'])
def nano_banana():
    prompt = request.args.get('prompt')
    image_url = request.args.get('url')

    if not prompt or not image_url:
        return jsonify({"success": False, "error": "Parameters missing"}), 400

    try:
        # 🛡️ ASLI GEMINI CALL
        # Hum Google ki official API ko instructions bhej rahe hain
        api_endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={GEMINI_API_KEY}"
        
        headers = {
            "Content-Type": "application/json",
            "Cookie": RAW_COOKIES # Cookies for authentication
        }

        payload = {
            "contents": [{
                "parts": [
                    {"text": f"Task: Image Editing. Instruction: {prompt}. Original Image URL: {image_url}. Output: Return the final edited image URL generated by Google Content CDN."},
                ]
            }]
        }

        response = requests.post(api_endpoint, headers=headers, json=payload)
        res_data = response.json()

        # Gemini se link extract karna
        # Agar Gemini link generate karta hai toh wo yahan aayega
        try:
            gemini_output = res_data['candidates'][0]['content']['parts'][0]['text'].strip()
            
            # Hum sirf tabhi success bhejenge agar Gemini ne koi URL diya ho
            if "http" in gemini_output:
                final_url = gemini_output
            else:
                # Agar Gemini link nahi de raha toh hum error denge, doosri API use nahi karenge
                return jsonify({
                    "success": False, 
                    "error": "Gemini didn't return a direct image link. Check prompt or cookies.",
                    "gemini_raw": gemini_output
                }), 500

        except:
            return jsonify({"success": False, "error": "Failed to parse Gemini response"}), 500

        return jsonify({
            "success": True,
            "status": 200,
            "author": "AHMAD RDX",
            "result": {
                "title": "NanoBanana Asli Gemini Edit",
                "prompt": prompt,
                "url": final_url
            }
        })

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=10000)
    
